### PR TITLE
a bigger set of changes - see descriptions for details

### PR DESCRIPTION
**Pull request by DEvil0000**
New features:
* remove interface configuration not configured in this role (can be turned on - off by default)
* interface config file prefix and postfix are configurable

improvements:
* restructured the role in more task files - maintainability
* network_pkgs is now overridable as configuration
* using handler for restarts
* updated meta file and readme

bugfixes:
* ansible deprecation warnings for some whens
* fixed wrong when var in redhat initial part
* also fixed test jobs for debain

### CODE REVIEW

**Comment by grastogi23** [comment]
Hi @ericsysmin 
can you also please reference the test automation for these changes as well. Like jenkins or saas tests.

thanks
Gaurav

**Comment by DEvil0000** [comment]
additionally fixed linter errors now

**Comment by ericsysmin** [comment]
I don't believe we have any, as we forked this role and i think it uses travis

**Comment by ericsysmin** [comment]
@grastogi23 I don't believe we have any, as we forked this role and i think it uses travis

**Pull request merged**
